import { fireEvent, render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, expect, it, vi } from 'vitest';
import { FeaturePlanAttachment } from './FeaturePlanAttachment';
import { readPlanFile, savePlanFile, downloadPlanFile, loadPlanFile } from './featurePlanFiles';

vi.mock('./featurePlanFiles', () => ({ readPlanFile: vi.fn(), savePlanFile: vi.fn(), downloadPlanFile: vi.fn(), loadPlanFile: vi.fn() }));
beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(readPlanFile).mockResolvedValue({ name: 'plan.md', content: '# Plan' });
  vi.mocked(savePlanFile).mockResolvedValue();
  vi.mocked(downloadPlanFile).mockResolvedValue();
  vi.mocked(loadPlanFile).mockResolvedValue({ name: 'plan.md', content: '# Plan\n\nBuild the feature.' });
  Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function (this: HTMLDialogElement) { this.setAttribute('open', ''); } });
  Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable: true, value: function (this: HTMLDialogElement) { this.removeAttribute('open'); } });
});
it('opens the filename in a viewer and downloads only through the download button', async () => {
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="plan.md" />);
  await actor.click(screen.getByRole('button', { name: 'View plan.md' }));
  const viewer = await screen.findByRole('dialog', { name: 'plan.md' });
  expect(within(viewer).getByText(/Build the feature/)).toBeVisible();
  expect(loadPlanFile).toHaveBeenCalledWith('idea-1');
  expect(downloadPlanFile).not.toHaveBeenCalled();
  await actor.click(within(viewer).getByRole('button', { name: 'Download' }));
  expect(downloadPlanFile).toHaveBeenCalledExactlyOnceWith('idea-1');
  await actor.click(within(viewer).getByRole('button', { name: 'Close plan viewer' }));
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
});
it('displays file text literally and supports dismissing with Escape', async () => {
  vi.mocked(loadPlanFile).mockResolvedValue({ name: 'plan.txt', content: '<script>alert(1)</script><img src="external" />' });
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="plan.txt" />);
  await actor.click(screen.getByRole('button', { name: 'View plan.txt' }));
  const viewer = await screen.findByRole('dialog', { name: 'plan.txt' });
  expect(viewer.querySelector('pre')).toHaveTextContent('<script>alert(1)</script>');
  expect(viewer.querySelector('script, img')).toBeNull();
  fireEvent(viewer, new Event('cancel', { cancelable: true }));
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
});
it('shows load failures in the viewer and retries without downloading', async () => {
  vi.mocked(loadPlanFile).mockRejectedValueOnce(new Error('Connection failed'));
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="plan.md" />);
  await actor.click(screen.getByRole('button', { name: 'View plan.md' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Connection failed');
  await actor.click(screen.getByRole('button', { name: 'Retry' }));
  expect(await screen.findByRole('dialog', { name: 'plan.md' })).toBeVisible();
  expect(downloadPlanFile).not.toHaveBeenCalled();
});
it('defaults Markdown to formatted headings, lists, tables and code, and toggles exact raw text', async () => {
  const markdown = '# Launch plan\n\nUse **careful testing** and `checks`.\n\n## Tasks\n\n- [x] Design\n- [ ] Build\n\n| Step | Owner |\n| --- | --- |\n| Test | Admin |\n\n```ts\nconst ready = true;\n```';
  vi.mocked(loadPlanFile).mockResolvedValue({ name: 'plan.MD', content: markdown });
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="plan.MD" />);
  await actor.click(screen.getByRole('button', { name: 'View plan.MD' }));
  const viewer = await screen.findByRole('dialog', { name: 'plan.MD' });
  expect(within(viewer).getByRole('button', { name: 'Formatted' })).toHaveAttribute('aria-pressed', 'true');
  expect(within(viewer).getByRole('heading', { name: 'Launch plan', level: 1 })).toBeVisible();
  expect(viewer.querySelector('strong')).toHaveTextContent('careful testing');
  expect(within(viewer).getAllByRole('checkbox')[0]).toBeChecked();
  expect(within(viewer).getByRole('table')).toHaveTextContent('TestAdmin');
  expect(viewer.querySelector('pre code')).toHaveTextContent('const ready = true;');
  await actor.click(within(viewer).getByRole('button', { name: 'Raw' }));
  expect(viewer.querySelector('pre')?.textContent).toBe(markdown);
  expect(within(viewer).queryByRole('table')).not.toBeInTheDocument();
  await actor.click(within(viewer).getByRole('button', { name: 'Formatted' }));
  expect(within(viewer).getByRole('table')).toBeVisible();
  expect(loadPlanFile).toHaveBeenCalledTimes(1);
  expect(downloadPlanFile).not.toHaveBeenCalled();
});
it('keeps HTML inert and blocks unsafe links in formatted Markdown', async () => {
  vi.mocked(loadPlanFile).mockResolvedValue({ name: 'plan.md', content: '<script>alert(1)</script>\n\n[Unsafe](javascript:evil) and [Docs](https://example.com)' });
  const open = vi.spyOn(window, 'open').mockImplementation(() => null);
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="plan.md" />);
  await actor.click(screen.getByRole('button', { name: 'View plan.md' }));
  const viewer = await screen.findByRole('dialog', { name: 'plan.md' });
  expect(viewer.querySelector('script')).toBeNull();
  await actor.click(within(viewer).getByRole('button', { name: 'Unsafe' }));
  expect(open).not.toHaveBeenCalled();
  await actor.click(within(viewer).getByRole('button', { name: 'Docs' }));
  expect(open).toHaveBeenCalledWith('https://example.com', '_blank', 'noopener,noreferrer');
});
it('uploads a plan to the right idea and exposes download and replace controls', async () => {
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" />);
  await actor.upload(screen.getByLabelText('Upload planning file for Search'), new File(['# Plan'], 'plan.md', { type: 'text/markdown' }));
  expect(await screen.findByText('Planning file saved.')).toBeInTheDocument();
  expect(savePlanFile).toHaveBeenCalledWith('idea-1', { name: 'plan.md', content: '# Plan' });
  expect(screen.getByText('Replace plan')).toBeInTheDocument();
  await actor.click(screen.getByRole('button', { name: 'Download plan.md' }));
  expect(downloadPlanFile).toHaveBeenCalledWith('idea-1');
});
it('keeps the old plan available after a failed replacement and allows retry', async () => {
  vi.mocked(savePlanFile).mockRejectedValueOnce(new Error('Upload failed'));
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="old.txt" />);
  const file = new File(['# Plan'], 'plan.md');
  await actor.upload(screen.getByLabelText('Upload planning file for Search'), file);
  expect(await screen.findByRole('alert')).toHaveTextContent('Upload failed');
  expect(screen.getByRole('button', { name: 'Download old.txt' })).toBeEnabled();
  await actor.upload(screen.getByLabelText('Upload planning file for Search'), file);
  expect(await screen.findByRole('button', { name: 'Download plan.md' })).toBeEnabled();
});
it('requires confirmation before removing the attachment', async () => {
  const actor = userEvent.setup();
  render(<FeaturePlanAttachment ideaId="idea-1" title="Search" initialName="old.txt" />);
  await actor.click(screen.getByRole('button', { name: 'Remove plan' }));
  expect(savePlanFile).not.toHaveBeenCalled();
  await actor.click(screen.getByRole('button', { name: 'Confirm removal' }));
  expect(await screen.findByText('Planning file removed.')).toBeInTheDocument();
  expect(savePlanFile).toHaveBeenCalledWith('idea-1', null);
  expect(screen.queryByRole('button', { name: 'Download old.txt' })).not.toBeInTheDocument();
});
